version: '2'

services:
  backend:
    image: backend
    depends_on:
      - db
    build:
      context: ./Backend
      dockerfile: Dockerfile
  db:
    image: postgres
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER:'waitless'
      - POSTGRES_PASSWORD:'waitless'
      - POSTGRES_DB:'waitless'

volumes:
  data:
    external: true